# Exploratory Data Analysis

In [52]:
# Import Pandas library
import pandas as pd

In [53]:
# Bring dataset into DataFrame
df = pd.read_csv('data/flash_floods_ky_2015_2025.csv')

In [54]:
# Read first rows of dataset
df.head()

,EVENT_ID,CZ_NAME_STR,BEGIN_LOCATION,BEGIN_DATE,BEGIN_TIME,EVENT_TYPE,MAGNITUDE,TOR_F_SCALE,DEATHS_DIRECT,INJURIES_DIRECT,...,END_AZIMUTH,END_LOCATION,END_DATE,END_TIME,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EVENT_NARRATIVE,EPISODE_NARRATIVE
0,564702,JEFFERSON CO.,SMYRNA,4/3/2015,348,Flash Flood,,,0,0,...,N,SMYRNA,4/3/2015,348,38.1500,-85.6600,38.1536,-85.6547,Law enforcement reported several water rescues...,A stalled frontal boundary across the area bro...
1,564703,JEFFERSON CO.,NEWBURG,4/3/2015,354,Flash Flood,,,0,0,...,WSW,NEWBURG,4/3/2015,354,38.1600,-85.7000,38.1633,-85.6969,Law enforcement reported evacuations at 6111 G...,A stalled frontal boundary across the area bro...
2,564704,ANDERSON CO.,LAWRENCEBURG,4/3/2015,400,Flash Flood,,,0,0,...,ESE,LAWRENCEBURG,4/3/2015,400,38.0229,-84.8866,38.0243,-84.8836,Emergency Management reported several roads cl...,A stalled frontal boundary across the area bro...
3,564706,SPENCER CO.,ELK CREEK,4/3/2015,400,Flash Flood,,,0,0,...,NNW,ELK CREEK,4/3/2015,400,38.0994,-85.3742,38.1038,-85.3727,State officials reported numerous water rescue...,A stalled frontal boundary across the area bro...
4,564705,JEFFERSON CO.,LOUISVILLE,4/3/2015,400,Flash Flood,,,0,0,...,SE,LOUISVILLE,4/3/2015,400,38.2300,-85.7800,38.2296,-85.7792,Law enforcement reported a road closure near 1...,A stalled frontal boundary across the area bro...

In [55]:
# Read last rows of dataset
df.tail()

,EVENT_ID,CZ_NAME_STR,BEGIN_LOCATION,BEGIN_DATE,BEGIN_TIME,EVENT_TYPE,MAGNITUDE,TOR_F_SCALE,DEATHS_DIRECT,INJURIES_DIRECT,...,END_AZIMUTH,END_LOCATION,END_DATE,END_TIME,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EVENT_NARRATIVE,EPISODE_NARRATIVE
1752,1297632,SPENCER CO.,WILSONVILLE,10/7/2025,1203,Flash Flood,,,0,0,...,NE,WATERFORD,10/7/2025,1303,38.1018,-85.4225,38.0623,-85.4013,There was water and debris over Plum Ridge Road.,As a couple of cold fronts moved through the L...
1753,1297629,JEFFERSON CO.,MINOR LANE HGTS,10/7/2025,1400,Flash Flood,,,0,0,...,NNW,MINOR LANE HGTS,10/7/2025,1500,38.1448,-85.7398,38.1446,-85.7372,Two men were standing on a rock with their lim...,As a couple of cold fronts moved through the L...
1754,1295858,FAYETTE CO.,(LEX)BLU GRS FLD LEX,10/7/2025,1430,Flash Flood,,,0,0,...,SW,SOUTH ELKHORN,10/7/2025,1630,38.0251,-84.5896,37.9979,-84.5823,Bowman Mill Road between Old Harrodsburg Road ...,As a couple of cold fronts moved through the L...
1755,1295859,FAYETTE CO.,YARNALLTON,10/7/2025,1433,Flash Flood,,,0,0,...,NW,YARNALLTON,10/7/2025,1633,38.1192,-84.6021,38.1434,-84.6502,Leestown Road between Dolan Lane and the Scott...,As a couple of cold fronts moved through the L...
1756,1295860,FAYETTE CO.,VILEY,10/7/2025,1436,Flash Flood,,,0,0,...,S,VILEY,10/7/2025,1636,38.0760,-84.5525,38.0748,-84.5509,Alexandria Drive between the Old Frankfort Pik...,As a couple of cold fronts moved through the L...

In [56]:
# Check data type and missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1757 entries, 0 to 1756
Data columns (total 38 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   EVENT_ID             1757 non-null   int64
 1   CZ_NAME_STR          1757 non-null   object
 2   BEGIN_LOCATION       1757 non-null   object
 3   BEGIN_DATE           1757 non-null   object
 4   BEGIN_TIME           1757 non-null   int64
 5   EVENT_TYPE           1757 non-null   object
 6   MAGNITUDE            1757 non-null   object
 7   TOR_F_SCALE          1757 non-null   object
 8   DEATHS_DIRECT        1757 non-null   int64
 9   INJURIES_DIRECT      1757 non-null   int64
 10  DAMAGE_PROPERTY_NUM  1757 non-null   int64
 11  DAMAGE_CROPS_NUM     1757 non-null   int64
 12  STATE_ABBR           1757 non-null   object
 13  CZ_TIMEZONE          1757 non-null   object
 14  MAGNITUDE_TYPE       1757 non-null   object
 15  EPISODE_ID           1757 non-null   int64
 16  CZ_TYPE              1757 non-null   object
 17  CZ_FIPS              1757 non-null   int64
 18  WFO                  1757 non-null   object
 19  INJURIES_INDIRECT    1757 non-null   int64
 20  DEATHS_INDIRECT      1757 non-null   int64
 21  SOURCE               1757 non-null   object
 22  FLOOD_CAUSE          1757 non-null   object
 23  TOR_LENGTH           1757 non-null   object
 24  TOR_WIDTH            1757 non-null   object
 25  BEGIN_RANGE          1757 non-null   float64
 26  BEGIN_AZIMUTH        1757 non-null   object
 27  END_RANGE            1757 non-null   float64
 28  END_AZIMUTH          1757 non-null   object
 29  END_LOCATION         1757 non-null   object
 30  END_DATE             1757 non-null   object
 31  END_TIME             1757 non-null   int64
 32  BEGIN_LAT            1757 non-null   float64
 33  BEGIN_LON            1757 non-null   float64
 34  END_LAT              1757 non-null   float64
 35  END_LON              1757 non-null   float64
 36  EVENT_NARRATIVE      1749 non-null   object
 37  EPISODE_NARRATIVE    1757 non-null   object
dtypes: float64(6), int64(11), object(21)
memory usage: 521.7+ KB

In [57]:
# See the dimensions of the dataset
df.shape

(1757, 38)

In [58]:
# Find categorical variables using .select_dtypes()
df.select_dtypes(include='object').columns

Index(['CZ_NAME_STR', 'BEGIN_LOCATION', 'BEGIN_DATE', 'EVENT_TYPE',
       'MAGNITUDE', 'TOR_F_SCALE', 'STATE_ABBR', 'CZ_TIMEZONE',
       'MAGNITUDE_TYPE', 'CZ_TYPE', 'WFO', 'SOURCE', 'FLOOD_CAUSE',
       'TOR_LENGTH', 'TOR_WIDTH', 'BEGIN_AZIMUTH', 'END_AZIMUTH',
       'END_LOCATION', 'END_DATE', 'EVENT_NARRATIVE', 'EPISODE_NARRATIVE'],
      dtype='object')

In [61]:
# Explore value counts for categorial variables
df.value_counts(subset=['EVENT_TYPE'])
df.value_counts(subset=['CZ_NAME_STR'])
df.value_counts(subset=['FLOOD_CAUSE'])

FLOOD_CAUSE
Heavy Rain                      1756
Heavy Rain / Tropical System       1
Name: count, dtype: int64

In [62]:
# Explore numberical columns
df.describe()

,EVENT_ID,BEGIN_TIME,DEATHS_DIRECT,INJURIES_DIRECT,DAMAGE_PROPERTY_NUM,DAMAGE_CROPS_NUM,EPISODE_ID,CZ_FIPS,INJURIES_INDIRECT,DEATHS_INDIRECT,BEGIN_RANGE,END_RANGE,END_TIME,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON
count,1.757000e+03,1757.000000,1757.000000,1757.000000,1.757000e+03,1757.000000,1757.000000,1757.000000,1757.0,1757.000000,1757.000000,1757.000000,1757.000000,1757.000000,1757.000000,1757.000000,1757.000000
mean,8.876687e+05,1335.211155,0.036426,0.009106,2.426549e+04,575.281730,145983.779169,118.640296,0.0,0.000569,1.286101,1.347621,1344.060330,37.602618,-85.139033,37.601395,-85.138703
std,2.194641e+05,630.683357,0.504913,0.358634,1.712214e+05,23857.141834,34467.116399,69.186638,0.0,0.023857,1.630638,1.617724,673.556341,0.611858,1.722825,0.609159,1.725535
min,5.583240e+05,0.000000,0.000000,0.000000,0.000000e+00,0.000000,93070.000000,1.000000,0.0,0.000000,0.000000,0.000000,0.000000,36.507000,-89.348400,36.500000,-89.245600
25%,6.911560e+05,830.000000,0.000000,0.000000,0.000000e+00,0.000000,115140.000000,59.000000,0.0,0.000000,0.620000,0.660000,830.000000,37.080000,-86.279100,37.089800,-86.273400
50%,8.973370e+05,1500.000000,0.000000,0.000000,0.000000e+00,0.000000,147970.000000,111.000000,0.0,0.000000,1.080000,1.100000,1500.000000,37.607800,-84.882600,37.611100,-84.867100
75%,1.049118e+06,1833.000000,0.000000,0.000000,1.000000e+03,0.000000,172563.000000,181.000000,0.0,0.000000,1.730000,1.740000,1900.000000,38.110000,-83.781400,38.101000,-83.780600
max,1.304116e+06,2359.000000,16.000000,15.000000,3.500000e+06,1000000.000000,207860.000000,239.000000,0.0,1.000000,47.680000,46.970000,2359.000000,39.100000,-82.063600,39.115200,-82.067500

In [63]:
# Filter rows using .loc[] ,.iloc[] and/or boolean indexing
df.loc[df['CZ_NAME_STR'] == 'Kentucky']
df.iloc[0:5]

,EVENT_ID,CZ_NAME_STR,BEGIN_LOCATION,BEGIN_DATE,BEGIN_TIME,EVENT_TYPE,MAGNITUDE,TOR_F_SCALE,DEATHS_DIRECT,INJURIES_DIRECT,...,END_AZIMUTH,END_LOCATION,END_DATE,END_TIME,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EVENT_NARRATIVE,EPISODE_NARRATIVE
0,564702,JEFFERSON CO.,SMYRNA,4/3/2015,348,Flash Flood,,,0,0,...,N,SMYRNA,4/3/2015,348,38.1500,-85.6600,38.1536,-85.6547,Law enforcement reported several water rescues...,A stalled frontal boundary across the area bro...
1,564703,JEFFERSON CO.,NEWBURG,4/3/2015,354,Flash Flood,,,0,0,...,WSW,NEWBURG,4/3/2015,354,38.1600,-85.7000,38.1633,-85.6969,Law enforcement reported evacuations at 6111 G...,A stalled frontal boundary across the area bro...
2,564704,ANDERSON CO.,LAWRENCEBURG,4/3/2015,400,Flash Flood,,,0,0,...,ESE,LAWRENCEBURG,4/3/2015,400,38.0229,-84.8866,38.0243,-84.8836,Emergency Management reported several roads cl...,A stalled frontal boundary across the area bro...
3,564706,SPENCER CO.,ELK CREEK,4/3/2015,400,Flash Flood,,,0,0,...,NNW,ELK CREEK,4/3/2015,400,38.0994,-85.3742,38.1038,-85.3727,State officials reported numerous water rescue...,A stalled frontal boundary across the area bro...
4,564705,JEFFERSON CO.,LOUISVILLE,4/3/2015,400,Flash Flood,,,0,0,...,SE,LOUISVILLE,4/3/2015,400,38.2300,-85.7800,38.2296,-85.7792,Law enforcement reported a road closure near 1...,A stalled frontal boundary across the area bro...

In [64]:
# Sort values using .sort_values()
df.sort_values(by='BEGIN_DATE', ascending=True)

,EVENT_ID,CZ_NAME_STR,BEGIN_LOCATION,BEGIN_DATE,BEGIN_TIME,EVENT_TYPE,MAGNITUDE,TOR_F_SCALE,DEATHS_DIRECT,INJURIES_DIRECT,...,END_AZIMUTH,END_LOCATION,END_DATE,END_TIME,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EVENT_NARRATIVE,EPISODE_NARRATIVE
1208,1004586,BREATHITT CO.,WHICK,1/1/2022,900,Flash Flood,,,0,0,...,WNW,LITTLE,1/1/2022,1115,37.4180,-83.3872,37.4343,-83.3833,Water was reported inside homes in the communi...,The second warmest December on record for East...
1203,1004929,ADAIR CO.,COBURG,1/1/2022,520,Flash Flood,,,0,0,...,N,COBURG,1/1/2022,720,37.2000,-85.3300,37.2028,-85.3300,Flash flooding occurred in Coburg. Damage amou...,"During New Year's Eve into New Year's Day, act..."
1204,1004346,FLOYD CO.,ARKANSAS,1/1/2022,757,Flash Flood,,,0,0,...,S,COLLIVER,1/1/2022,1145,37.5829,-82.7376,37.5922,-82.7306,Reports that water rescues were being performe...,The second warmest December on record for East...
1205,1005229,PIKE CO.,BELFRY,1/1/2022,817,Flash Flood,,,0,0,...,ESE,LECKIEVILLE,1/1/2022,1145,37.6158,-82.2808,37.6250,-82.2853,Water is reported to be in homes in the Belfry...,The second warmest December on record for East...
1206,1004352,BREATHITT CO.,CANOE,1/1/2022,830,Flash Flood,,,0,0,...,NNW,CANOE,1/1/2022,1115,37.4486,-83.4520,37.4565,-83.4522,A report came in that water rescues were being...,The second warmest December on record for East...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
651,773419,MENIFEE CO.,ROTHWELL,9/9/2018,1656,Flash Flood,,,0,0,...,N,ROTHWELL,9/9/2018,1906,37.9700,-83.7000,37.9709,-83.7011,A local media outlet reported water flowing ac...,"A slow moving low pressure system, in combinat..."
652,773420,ESTILL CO.,RAVENNA,9/9/2018,1825,Flash Flood,,,0,0,...,NE,PRYSE,9/9/2018,1855,37.6900,-83.9500,37.6944,-83.8559,Dispatch reported water flowing over several r...,"A slow moving low pressure system, in combinat..."
653,773422,POWELL CO.,WALTERSVILLE,9/9/2018,1835,Flash Flood,,,0,0,...,SSW,WALTERSVILLE,9/9/2018,2055,37.8600,-83.9400,37.8582,-83.9385,Water was observed rushing across Adams Ridges...,"A slow moving low pressure system, in combinat..."
649,783660,JESSAMINE CO.,UNION MILLS,9/9/2018,1441,Flash Flood,,,0,0,...,NNE,UNION MILLS,9/9/2018,1511,37.9100,-84.5000,37.9123,-84.4958,Mackey Pike near Hickman Creek was closed due ...,"On September 5, 2018, the remnants of Tropical..."
647,773418,MENIFEE CO.,DENNISTON,9/9/2018,1430,Flash Flood,,,0,0,...,NNW,FRENCHBURG,9/9/2018,1630,37.9472,-83.5458,37.9670,-83.6350,"Water flowed across most county roads, resulti...","A slow moving low pressure system, in combinat..."

In [65]:
# Rename columns using .rename()
df.rename(columns={'CZ_NAME_STR': 'COUNTY_NAME'}, inplace=True)

In [66]:
# Drop columns using .drop()
df.drop(columns=['MAGNITUDE', 'TOR_F_SCALE', 'TOR_LENGTH', 'TOR_WIDTH' ], inplace=True)

In [68]:
# Fix data types using .astype()
df.astype({'BEGIN_DATE': 'datetime64[ns]'})
df.astype({'END_DATE': 'datetime64[ns]'})
df.astype({'EVENT_NARRATIVE': 'string'})
df.astype({'EPISODE_NARRATIVE': 'string'})

,EVENT_ID,COUNTY_NAME,BEGIN_LOCATION,BEGIN_DATE,BEGIN_TIME,EVENT_TYPE,DEATHS_DIRECT,INJURIES_DIRECT,DAMAGE_PROPERTY_NUM,DAMAGE_CROPS_NUM,...,END_AZIMUTH,END_LOCATION,END_DATE,END_TIME,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EVENT_NARRATIVE,EPISODE_NARRATIVE
0,564702,JEFFERSON CO.,SMYRNA,4/3/2015,348,Flash Flood,0,0,0,0,...,N,SMYRNA,4/3/2015,348,38.1500,-85.6600,38.1536,-85.6547,Law enforcement reported several water rescues...,A stalled frontal boundary across the area bro...
1,564703,JEFFERSON CO.,NEWBURG,4/3/2015,354,Flash Flood,0,0,20000,0,...,WSW,NEWBURG,4/3/2015,354,38.1600,-85.7000,38.1633,-85.6969,Law enforcement reported evacuations at 6111 G...,A stalled frontal boundary across the area bro...
2,564704,ANDERSON CO.,LAWRENCEBURG,4/3/2015,400,Flash Flood,0,0,30000,0,...,ESE,LAWRENCEBURG,4/3/2015,400,38.0229,-84.8866,38.0243,-84.8836,Emergency Management reported several roads cl...,A stalled frontal boundary across the area bro...
3,564706,SPENCER CO.,ELK CREEK,4/3/2015,400,Flash Flood,0,0,30000,0,...,NNW,ELK CREEK,4/3/2015,400,38.0994,-85.3742,38.1038,-85.3727,State officials reported numerous water rescue...,A stalled frontal boundary across the area bro...
4,564705,JEFFERSON CO.,LOUISVILLE,4/3/2015,400,Flash Flood,0,0,0,0,...,SE,LOUISVILLE,4/3/2015,400,38.2300,-85.7800,38.2296,-85.7792,Law enforcement reported a road closure near 1...,A stalled frontal boundary across the area bro...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1752,1297632,SPENCER CO.,WILSONVILLE,10/7/2025,1203,Flash Flood,0,0,0,0,...,NE,WATERFORD,10/7/2025,1303,38.1018,-85.4225,38.0623,-85.4013,There was water and debris over Plum Ridge Road.,As a couple of cold fronts moved through the L...
1753,1297629,JEFFERSON CO.,MINOR LANE HGTS,10/7/2025,1400,Flash Flood,0,0,0,0,...,NNW,MINOR LANE HGTS,10/7/2025,1500,38.1448,-85.7398,38.1446,-85.7372,Two men were standing on a rock with their lim...,As a couple of cold fronts moved through the L...
1754,1295858,FAYETTE CO.,(LEX)BLU GRS FLD LEX,10/7/2025,1430,Flash Flood,0,0,0,0,...,SW,SOUTH ELKHORN,10/7/2025,1630,38.0251,-84.5896,37.9979,-84.5823,Bowman Mill Road between Old Harrodsburg Road ...,As a couple of cold fronts moved through the L...
1755,1295859,FAYETTE CO.,YARNALLTON,10/7/2025,1433,Flash Flood,0,0,0,0,...,NW,YARNALLTON,10/7/2025,1633,38.1192,-84.6021,38.1434,-84.6502,Leestown Road between Dolan Lane and the Scott...,As a couple of cold fronts moved through the L...
1756,1295860,FAYETTE CO.,VILEY,10/7/2025,1436,Flash Flood,0,0,0,0,...,S,VILEY,10/7/2025,1636,38.0760,-84.5525,38.0748,-84.5509,Alexandria Drive between the Old Frankfort Pik...,As a couple of cold fronts moved through the L...

In [70]:
# Identify missing values using .isnull() and/or .notnull()
df.isnull().sum()

EVENT_ID               0
COUNTY_NAME            0
BEGIN_LOCATION         0
BEGIN_DATE             0
BEGIN_TIME             0
EVENT_TYPE             0
DEATHS_DIRECT          0
INJURIES_DIRECT        0
DAMAGE_PROPERTY_NUM    0
DAMAGE_CROPS_NUM       0
STATE_ABBR             0
CZ_TIMEZONE            0
MAGNITUDE_TYPE         0
EPISODE_ID             0
CZ_TYPE                0
CZ_FIPS                0
WFO                    0
INJURIES_INDIRECT      0
DEATHS_INDIRECT        0
SOURCE                 0
FLOOD_CAUSE            0
BEGIN_RANGE            0
BEGIN_AZIMUTH          0
END_RANGE              0
END_AZIMUTH            0
END_LOCATION           0
END_DATE               0
END_TIME               0
BEGIN_LAT              0
BEGIN_LON              0
END_LAT                0
END_LON                0
EVENT_NARRATIVE        8
EPISODE_NARRATIVE      0
dtype: int64

In [71]:
# Check for duplicate rows using .duplicated()
df.duplicated().sum()

np.int64(0)