# Flash Floods KY Combined Data EDA

In [33]:
# Import libraries and dependencies
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.transforms as mtransforms
import seaborn as sns
import pandas as pd
import numpy as np
import sqlite3

In [34]:
# Read dataset into dataframe
df = pd.read_csv('../data/processed/flash_floods_ky_combined_data.csv')

In [35]:
# Read first rows of dataset
df.head()

,event_id,county_name,begin_location,begin_date,begin_time,begin_range,end_range,end_location,end_date,end_time,...,mintemp_f,avgtemp_f,maxwind_mph,totalprecip_in,avgvis_miles,avghumidity,uv,daily_will_it_rain,daily_chance_of_rain,condition_text
0,564702,JEFFERSON CO.,SMYRNA,2015-04-03,348,1.48,1.28,SMYRNA,2015-04-03,348,...,45.3,58.9,13.9,2.19,4.0,95,2.7,1,100,Moderate or heavy rain shower
1,564703,JEFFERSON CO.,NEWBURG,2015-04-03,354,1.29,1.47,NEWBURG,2015-04-03,354,...,45.3,58.9,13.9,2.19,4.0,95,2.7,1,100,Moderate or heavy rain shower
2,564704,ANDERSON CO.,LAWRENCEBURG,2015-04-03,400,0.88,1.09,LAWRENCEBURG,2015-04-03,400,...,45.4,59.1,17.7,2.67,4.0,96,1.3,1,100,Moderate or heavy rain shower
3,564706,SPENCER CO.,ELK CREEK,2015-04-03,400,0.23,0.05,ELK CREEK,2015-04-03,400,...,45.0,58.7,15.4,2.65,3.0,95,1.9,1,100,Moderate or heavy rain shower
4,564705,JEFFERSON CO.,LOUISVILLE,2015-04-03,400,0.00,0.21,LOUISVILLE,2015-04-03,400,...,44.8,58.2,13.0,2.03,4.0,95,2.7,1,100,Moderate or heavy rain shower

In [36]:
# Read last rows of dataset
df.tail()

,event_id,county_name,begin_location,begin_date,begin_time,begin_range,end_range,end_location,end_date,end_time,...,mintemp_f,avgtemp_f,maxwind_mph,totalprecip_in,avgvis_miles,avghumidity,uv,daily_will_it_rain,daily_chance_of_rain,condition_text
1752,1297632,SPENCER CO.,WILSONVILLE,2025-10-07,1203,1.76,1.35,WATERFORD,2025-10-07,1303,...,65.1,66.6,6.9,1.25,3.0,96,2.6,1,100,Moderate or heavy rain shower
1753,1297629,JEFFERSON CO.,MINOR LANE HGTS,2025-10-07,1400,1.15,1.10,MINOR LANE HGTS,2025-10-07,1500,...,66.6,68.4,5.8,1.09,4.0,95,2.6,1,100,Heavy rain
1754,1295858,FAYETTE CO.,(LEX)BLU GRS FLD LEX,2025-10-07,1430,0.66,0.47,SOUTH ELKHORN,2025-10-07,1630,...,64.9,66.1,8.9,1.22,3.0,94,3.1,1,100,Heavy rain
1755,1295859,FAYETTE CO.,YARNALLTON,2025-10-07,1433,1.79,1.85,YARNALLTON,2025-10-07,1633,...,64.9,66.1,8.9,1.22,3.0,94,3.1,1,100,Heavy rain
1756,1295860,FAYETTE CO.,VILEY,2025-10-07,1436,0.31,0.78,VILEY,2025-10-07,1636,...,64.9,66.1,8.9,1.22,3.0,94,3.1,1,100,Heavy rain

In [37]:
# Check data type and missing values
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1757 entries, 0 to 1756
Data columns (total 57 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   event_id                           1757 non-null   int64
 1   county_name                        1757 non-null   str
 2   begin_location                     1757 non-null   str
 3   begin_date                         1757 non-null   str
 4   begin_time                         1757 non-null   int64
 5   begin_range                        1757 non-null   float64
 6   end_range                          1757 non-null   float64
 7   end_location                       1757 non-null   str
 8   end_date                           1757 non-null   str
 9   end_time                           1757 non-null   int64
 10  begin_lat                          1757 non-null   float64
 11  begin_lon                          1757 non-null   float64
 12  end_lat                            1757 non-null   float64
 13  end_lon                            1757 non-null   float64
 14  year                               1757 non-null   int64
 15  duration_minutes                   1757 non-null   float64
 16  duration_hours                     1757 non-null   float64
 17  deaths_direct                      1757 non-null   int64
 18  injuries_direct                    1757 non-null   int64
 19  damage_property_num                1757 non-null   int64
 20  damage_crops_num                   1757 non-null   int64
 21  injuries_indirect                  1757 non-null   int64
 22  deaths_indirect                    1757 non-null   int64
 23  sun_altitude_deg                   1757 non-null   float64
 24  sun_azimuth_deg                    1757 non-null   float64
 25  sunrise_utc                        1757 non-null   str
 26  sunset_utc                         1757 non-null   str
 27  moon_altitude_deg                  1757 non-null   float64
 28  moon_azimuth_deg                   1757 non-null   float64
 29  moon_phase_name                    1757 non-null   str
 30  moon_illumination_pct              1757 non-null   float64
 31  nlcd_code                          1757 non-null   int64
 32  nlcd_class                         1757 non-null   str
 33  elevation_m                        1757 non-null   float64
 34  impervious_surface_pct             1757 non-null   int64
 35  oni_season                         1757 non-null   str
 36  oni_anomaly                        1757 non-null   float64
 37  enso_phase                         1757 non-null   str
 38  soil_moisture_0_to_100cm_mean      1757 non-null   float64
 39  soil_moisture_0_to_7cm_mean        1757 non-null   float64
 40  soil_moisture_28_to_100cm_mean     1757 non-null   float64
 41  soil_moisture_7_to_28cm_mean       1757 non-null   float64
 42  soil_temperature_0_to_100cm_mean   1757 non-null   float64
 43  soil_temperature_0_to_7cm_mean     1757 non-null   float64
 44  soil_temperature_28_to_100cm_mean  1757 non-null   float64
 45  soil_temperature_7_to_28cm_mean    1757 non-null   float64
 46  maxtemp_f                          1757 non-null   float64
 47  mintemp_f                          1757 non-null   float64
 48  avgtemp_f                          1757 non-null   float64
 49  maxwind_mph                        1757 non-null   float64
 50  totalprecip_in                     1757 non-null   float64
 51  avgvis_miles                       1757 non-null   float64
 52  avghumidity                        1757 non-null   int64
 53  uv                                 1757 non-null   float64
 54  daily_will_it_rain                 1757 non-null   int64
 55  daily_chance_of_rain               1757 non-null   int64
 56  condition_text                     1757 non-null   str
dtypes: float64(30), int64(15), str(12)
memory usage: 1.0 MB

In [38]:
# See the dimensions of the dataset
df.shape

(1757, 57)

In [39]:
# Strip hidden spaces from all column names
df.columns = df.columns.str.strip()

In [40]:
# Convert event_id to string
df['event_id'] = df['event_id'].astype(str)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1757 entries, 0 to 1756
Data columns (total 57 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   event_id                           1757 non-null   str
 1   county_name                        1757 non-null   str
 2   begin_location                     1757 non-null   str
 3   begin_date                         1757 non-null   str
 4   begin_time                         1757 non-null   int64
 5   begin_range                        1757 non-null   float64
 6   end_range                          1757 non-null   float64
 7   end_location                       1757 non-null   str
 8   end_date                           1757 non-null   str
 9   end_time                           1757 non-null   int64
 10  begin_lat                          1757 non-null   float64
 11  begin_lon                          1757 non-null   float64
 12  end_lat                            1757 non-null   float64
 13  end_lon                            1757 non-null   float64
 14  year                               1757 non-null   int64
 15  duration_minutes                   1757 non-null   float64
 16  duration_hours                     1757 non-null   float64
 17  deaths_direct                      1757 non-null   int64
 18  injuries_direct                    1757 non-null   int64
 19  damage_property_num                1757 non-null   int64
 20  damage_crops_num                   1757 non-null   int64
 21  injuries_indirect                  1757 non-null   int64
 22  deaths_indirect                    1757 non-null   int64
 23  sun_altitude_deg                   1757 non-null   float64
 24  sun_azimuth_deg                    1757 non-null   float64
 25  sunrise_utc                        1757 non-null   str
 26  sunset_utc                         1757 non-null   str
 27  moon_altitude_deg                  1757 non-null   float64
 28  moon_azimuth_deg                   1757 non-null   float64
 29  moon_phase_name                    1757 non-null   str
 30  moon_illumination_pct              1757 non-null   float64
 31  nlcd_code                          1757 non-null   int64
 32  nlcd_class                         1757 non-null   str
 33  elevation_m                        1757 non-null   float64
 34  impervious_surface_pct             1757 non-null   int64
 35  oni_season                         1757 non-null   str
 36  oni_anomaly                        1757 non-null   float64
 37  enso_phase                         1757 non-null   str
 38  soil_moisture_0_to_100cm_mean      1757 non-null   float64
 39  soil_moisture_0_to_7cm_mean        1757 non-null   float64
 40  soil_moisture_28_to_100cm_mean     1757 non-null   float64
 41  soil_moisture_7_to_28cm_mean       1757 non-null   float64
 42  soil_temperature_0_to_100cm_mean   1757 non-null   float64
 43  soil_temperature_0_to_7cm_mean     1757 non-null   float64
 44  soil_temperature_28_to_100cm_mean  1757 non-null   float64
 45  soil_temperature_7_to_28cm_mean    1757 non-null   float64
 46  maxtemp_f                          1757 non-null   float64
 47  mintemp_f                          1757 non-null   float64
 48  avgtemp_f                          1757 non-null   float64
 49  maxwind_mph                        1757 non-null   float64
 50  totalprecip_in                     1757 non-null   float64
 51  avgvis_miles                       1757 non-null   float64
 52  avghumidity                        1757 non-null   int64
 53  uv                                 1757 non-null   float64
 54  daily_will_it_rain                 1757 non-null   int64
 55  daily_chance_of_rain               1757 non-null   int64
 56  condition_text                     1757 non-null   str
dtypes: float64(30), int64(14), str(13)
memory usage: 1.0 MB

In [41]:
# Convert date strings to datetime objects
df['begin_date'] = pd.to_datetime(df['begin_date'], format='mixed')
df['end_date'] = pd.to_datetime(df['end_date'], format='mixed')

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1757 entries, 0 to 1756
Data columns (total 57 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   event_id                           1757 non-null   str
 1   county_name                        1757 non-null   str
 2   begin_location                     1757 non-null   str
 3   begin_date                         1757 non-null   datetime64[us]
 4   begin_time                         1757 non-null   int64
 5   begin_range                        1757 non-null   float64
 6   end_range                          1757 non-null   float64
 7   end_location                       1757 non-null   str
 8   end_date                           1757 non-null   datetime64[us]
 9   end_time                           1757 non-null   int64
 10  begin_lat                          1757 non-null   float64
 11  begin_lon                          1757 non-null   float64
 12  end_lat                            1757 non-null   float64
 13  end_lon                            1757 non-null   float64
 14  year                               1757 non-null   int64
 15  duration_minutes                   1757 non-null   float64
 16  duration_hours                     1757 non-null   float64
 17  deaths_direct                      1757 non-null   int64
 18  injuries_direct                    1757 non-null   int64
 19  damage_property_num                1757 non-null   int64
 20  damage_crops_num                   1757 non-null   int64
 21  injuries_indirect                  1757 non-null   int64
 22  deaths_indirect                    1757 non-null   int64
 23  sun_altitude_deg                   1757 non-null   float64
 24  sun_azimuth_deg                    1757 non-null   float64
 25  sunrise_utc                        1757 non-null   str
 26  sunset_utc                         1757 non-null   str
 27  moon_altitude_deg                  1757 non-null   float64
 28  moon_azimuth_deg                   1757 non-null   float64
 29  moon_phase_name                    1757 non-null   str
 30  moon_illumination_pct              1757 non-null   float64
 31  nlcd_code                          1757 non-null   int64
 32  nlcd_class                         1757 non-null   str
 33  elevation_m                        1757 non-null   float64
 34  impervious_surface_pct             1757 non-null   int64
 35  oni_season                         1757 non-null   str
 36  oni_anomaly                        1757 non-null   float64
 37  enso_phase                         1757 non-null   str
 38  soil_moisture_0_to_100cm_mean      1757 non-null   float64
 39  soil_moisture_0_to_7cm_mean        1757 non-null   float64
 40  soil_moisture_28_to_100cm_mean     1757 non-null   float64
 41  soil_moisture_7_to_28cm_mean       1757 non-null   float64
 42  soil_temperature_0_to_100cm_mean   1757 non-null   float64
 43  soil_temperature_0_to_7cm_mean     1757 non-null   float64
 44  soil_temperature_28_to_100cm_mean  1757 non-null   float64
 45  soil_temperature_7_to_28cm_mean    1757 non-null   float64
 46  maxtemp_f                          1757 non-null   float64
 47  mintemp_f                          1757 non-null   float64
 48  avgtemp_f                          1757 non-null   float64
 49  maxwind_mph                        1757 non-null   float64
 50  totalprecip_in                     1757 non-null   float64
 51  avgvis_miles                       1757 non-null   float64
 52  avghumidity                        1757 non-null   int64
 53  uv                                 1757 non-null   float64
 54  daily_will_it_rain                 1757 non-null   int64
 55  daily_chance_of_rain               1757 non-null   int64
 56  condition_text                     1757 non-null   str
dtypes: datetime64[us](2), float64(30), int64(14), str(11)
memory usage: 1023.1 KB

In [42]:
# Standardize time ints into 4-digit strings
df['begin_time'] = df['begin_time'].astype(str).str.zfill(4)
df['end_time'] = df['end_time'].astype(str).str.zfill(4)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1757 entries, 0 to 1756
Data columns (total 57 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   event_id                           1757 non-null   str
 1   county_name                        1757 non-null   str
 2   begin_location                     1757 non-null   str
 3   begin_date                         1757 non-null   datetime64[us]
 4   begin_time                         1757 non-null   str
 5   begin_range                        1757 non-null   float64
 6   end_range                          1757 non-null   float64
 7   end_location                       1757 non-null   str
 8   end_date                           1757 non-null   datetime64[us]
 9   end_time                           1757 non-null   str
 10  begin_lat                          1757 non-null   float64
 11  begin_lon                          1757 non-null   float64
 12  end_lat                            1757 non-null   float64
 13  end_lon                            1757 non-null   float64
 14  year                               1757 non-null   int64
 15  duration_minutes                   1757 non-null   float64
 16  duration_hours                     1757 non-null   float64
 17  deaths_direct                      1757 non-null   int64
 18  injuries_direct                    1757 non-null   int64
 19  damage_property_num                1757 non-null   int64
 20  damage_crops_num                   1757 non-null   int64
 21  injuries_indirect                  1757 non-null   int64
 22  deaths_indirect                    1757 non-null   int64
 23  sun_altitude_deg                   1757 non-null   float64
 24  sun_azimuth_deg                    1757 non-null   float64
 25  sunrise_utc                        1757 non-null   str
 26  sunset_utc                         1757 non-null   str
 27  moon_altitude_deg                  1757 non-null   float64
 28  moon_azimuth_deg                   1757 non-null   float64
 29  moon_phase_name                    1757 non-null   str
 30  moon_illumination_pct              1757 non-null   float64
 31  nlcd_code                          1757 non-null   int64
 32  nlcd_class                         1757 non-null   str
 33  elevation_m                        1757 non-null   float64
 34  impervious_surface_pct             1757 non-null   int64
 35  oni_season                         1757 non-null   str
 36  oni_anomaly                        1757 non-null   float64
 37  enso_phase                         1757 non-null   str
 38  soil_moisture_0_to_100cm_mean      1757 non-null   float64
 39  soil_moisture_0_to_7cm_mean        1757 non-null   float64
 40  soil_moisture_28_to_100cm_mean     1757 non-null   float64
 41  soil_moisture_7_to_28cm_mean       1757 non-null   float64
 42  soil_temperature_0_to_100cm_mean   1757 non-null   float64
 43  soil_temperature_0_to_7cm_mean     1757 non-null   float64
 44  soil_temperature_28_to_100cm_mean  1757 non-null   float64
 45  soil_temperature_7_to_28cm_mean    1757 non-null   float64
 46  maxtemp_f                          1757 non-null   float64
 47  mintemp_f                          1757 non-null   float64
 48  avgtemp_f                          1757 non-null   float64
 49  maxwind_mph                        1757 non-null   float64
 50  totalprecip_in                     1757 non-null   float64
 51  avgvis_miles                       1757 non-null   float64
 52  avghumidity                        1757 non-null   int64
 53  uv                                 1757 non-null   float64
 54  daily_will_it_rain                 1757 non-null   int64
 55  daily_chance_of_rain               1757 non-null   int64
 56  condition_text                     1757 non-null   str
dtypes: datetime64[us](2), float64(30), int64(12), str(13)
memory usage: 1.0 MB

In [43]:
# Create unified datetime series
df['start_datetime'] = pd.to_datetime( df['begin_date'].dt.strftime('%Y-%m-%d') + ' ' + df['begin_time'], format='%Y-%m-%d %H%M' ) 
df['end_datetime'] = pd.to_datetime( df['end_date'].dt.strftime('%Y-%m-%d') + ' ' + df['end_time'], format='%Y-%m-%d %H%M' )

In [ ]:
# Move newly formed columns to after event_id column
start_datetime = df.pop('start_datetime')
end_datetime = df.pop('end_datetime')

df.insert(1, 'start_datetime', start_datetime)
df.insert(2, 'end_datetime', end_datetime)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1757 entries, 0 to 1756
Data columns (total 59 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   event_id                           1757 non-null   str
 1   start_datetime                     1757 non-null   datetime64[us]
 2   end_datetime                       1757 non-null   datetime64[us]
 3   county_name                        1757 non-null   str
 4   begin_location                     1757 non-null   str
 5   begin_date                         1757 non-null   datetime64[us]
 6   begin_time                         1757 non-null   str
 7   begin_range                        1757 non-null   float64
 8   end_range                          1757 non-null   float64
 9   end_location                       1757 non-null   str
 10  end_date                           1757 non-null   datetime64[us]
 11  end_time                           1757 non-null   str
 12  begin_lat                          1757 non-null   float64
 13  begin_lon                          1757 non-null   float64
 14  end_lat                            1757 non-null   float64
 15  end_lon                            1757 non-null   float64
 16  year                               1757 non-null   int64
 17  duration_minutes                   1757 non-null   float64
 18  duration_hours                     1757 non-null   float64
 19  deaths_direct                      1757 non-null   int64
 20  injuries_direct                    1757 non-null   int64
 21  damage_property_num                1757 non-null   int64
 22  damage_crops_num                   1757 non-null   int64
 23  injuries_indirect                  1757 non-null   int64
 24  deaths_indirect                    1757 non-null   int64
 25  sun_altitude_deg                   1757 non-null   float64
 26  sun_azimuth_deg                    1757 non-null   float64
 27  sunrise_utc                        1757 non-null   str
 28  sunset_utc                         1757 non-null   str
 29  moon_altitude_deg                  1757 non-null   float64
 30  moon_azimuth_deg                   1757 non-null   float64
 31  moon_phase_name                    1757 non-null   str
 32  moon_illumination_pct              1757 non-null   float64
 33  nlcd_code                          1757 non-null   int64
 34  nlcd_class                         1757 non-null   str
 35  elevation_m                        1757 non-null   float64
 36  impervious_surface_pct             1757 non-null   int64
 37  oni_season                         1757 non-null   str
 38  oni_anomaly                        1757 non-null   float64
 39  enso_phase                         1757 non-null   str
 40  soil_moisture_0_to_100cm_mean      1757 non-null   float64
 41  soil_moisture_0_to_7cm_mean        1757 non-null   float64
 42  soil_moisture_28_to_100cm_mean     1757 non-null   float64
 43  soil_moisture_7_to_28cm_mean       1757 non-null   float64
 44  soil_temperature_0_to_100cm_mean   1757 non-null   float64
 45  soil_temperature_0_to_7cm_mean     1757 non-null   float64
 46  soil_temperature_28_to_100cm_mean  1757 non-null   float64
 47  soil_temperature_7_to_28cm_mean    1757 non-null   float64
 48  maxtemp_f                          1757 non-null   float64
 49  mintemp_f                          1757 non-null   float64
 50  avgtemp_f                          1757 non-null   float64
 51  maxwind_mph                        1757 non-null   float64
 52  totalprecip_in                     1757 non-null   float64
 53  avgvis_miles                       1757 non-null   float64
 54  avghumidity                        1757 non-null   int64
 55  uv                                 1757 non-null   float64
 56  daily_will_it_rain                 1757 non-null   int64
 57  daily_chance_of_rain               1757 non-null   int64
 58  condition_text                     1757 non-null   str
dtypes: datetime64[us](4), float64(30), int64(12), str(13)
memory usage: 1.0 MB

In [ ]:
# Drop columns
df = df.drop(columns=[
    'begin_date',
    'end_date',
    'begin_time',
    'end_time'
])

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1757 entries, 0 to 1756
Data columns (total 55 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   event_id                           1757 non-null   str
 1   start_datetime                     1757 non-null   datetime64[us]
 2   end_datetime                       1757 non-null   datetime64[us]
 3   county_name                        1757 non-null   str
 4   begin_location                     1757 non-null   str
 5   begin_range                        1757 non-null   float64
 6   end_range                          1757 non-null   float64
 7   end_location                       1757 non-null   str
 8   begin_lat                          1757 non-null   float64
 9   begin_lon                          1757 non-null   float64
 10  end_lat                            1757 non-null   float64
 11  end_lon                            1757 non-null   float64
 12  year                               1757 non-null   int64
 13  duration_minutes                   1757 non-null   float64
 14  duration_hours                     1757 non-null   float64
 15  deaths_direct                      1757 non-null   int64
 16  injuries_direct                    1757 non-null   int64
 17  damage_property_num                1757 non-null   int64
 18  damage_crops_num                   1757 non-null   int64
 19  injuries_indirect                  1757 non-null   int64
 20  deaths_indirect                    1757 non-null   int64
 21  sun_altitude_deg                   1757 non-null   float64
 22  sun_azimuth_deg                    1757 non-null   float64
 23  sunrise_utc                        1757 non-null   str
 24  sunset_utc                         1757 non-null   str
 25  moon_altitude_deg                  1757 non-null   float64
 26  moon_azimuth_deg                   1757 non-null   float64
 27  moon_phase_name                    1757 non-null   str
 28  moon_illumination_pct              1757 non-null   float64
 29  nlcd_code                          1757 non-null   int64
 30  nlcd_class                         1757 non-null   str
 31  elevation_m                        1757 non-null   float64
 32  impervious_surface_pct             1757 non-null   int64
 33  oni_season                         1757 non-null   str
 34  oni_anomaly                        1757 non-null   float64
 35  enso_phase                         1757 non-null   str
 36  soil_moisture_0_to_100cm_mean      1757 non-null   float64
 37  soil_moisture_0_to_7cm_mean        1757 non-null   float64
 38  soil_moisture_28_to_100cm_mean     1757 non-null   float64
 39  soil_moisture_7_to_28cm_mean       1757 non-null   float64
 40  soil_temperature_0_to_100cm_mean   1757 non-null   float64
 41  soil_temperature_0_to_7cm_mean     1757 non-null   float64
 42  soil_temperature_28_to_100cm_mean  1757 non-null   float64
 43  soil_temperature_7_to_28cm_mean    1757 non-null   float64
 44  maxtemp_f                          1757 non-null   float64
 45  mintemp_f                          1757 non-null   float64
 46  avgtemp_f                          1757 non-null   float64
 47  maxwind_mph                        1757 non-null   float64
 48  totalprecip_in                     1757 non-null   float64
 49  avgvis_miles                       1757 non-null   float64
 50  avghumidity                        1757 non-null   int64
 51  uv                                 1757 non-null   float64
 52  daily_will_it_rain                 1757 non-null   int64
 53  daily_chance_of_rain               1757 non-null   int64
 54  condition_text                     1757 non-null   str
dtypes: datetime64[us](2), float64(30), int64(12), str(11)
memory usage: 995.7 KB

In [46]:
# Save dataframe to CSV file
df.to_csv('../data/processed/flash_floods_ky_combined_data.csv', index=False)